
// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using PaymentCheckService;
//
//    var customers = Customers.FromJson(jsonString);

namespace PaymentAPI
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CustomersDatum
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("account_balance")]
        public long AccountBalance { get; set; }

        [JsonProperty("address")]
        public object Address { get; set; }

        [JsonProperty("balance")]
        public long Balance { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("default_source")]
        public string DefaultSource { get; set; }

        [JsonProperty("delinquent")]
        public bool Delinquent { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("discount")]
        public object Discount { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("invoice_prefix")]
        public string InvoicePrefix { get; set; }

        [JsonProperty("invoice_settings")]
        public InvoiceSettings InvoiceSettings { get; set; }

        [JsonProperty("livemode")]
        public bool Livemode { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("name")]
        public object Name { get; set; }

        [JsonProperty("phone")]
        public object Phone { get; set; }

        [JsonProperty("preferred_locales")]
        public List<object> PreferredLocales { get; set; }

        [JsonProperty("shipping")]
        public object Shipping { get; set; }

        [JsonProperty("sources")]
        public Sources Sources { get; set; }

        [JsonProperty("subscriptions")]
        public Subscriptions Subscriptions { get; set; }

        [JsonProperty("tax_exempt")]
        public string TaxExempt { get; set; }

        [JsonProperty("tax_ids")]
        public Customers TaxIds { get; set; }

        [JsonProperty("tax_info")]
        public object TaxInfo { get; set; }

        [JsonProperty("tax_info_verification")]
        public object TaxInfoVerification { get; set; }
    }

    public partial class Customers
    {
        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("data")]
        public List<CustomersDatum> Data { get; set; }

        [JsonProperty("has_more")]
        public bool HasMore { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("total_count", NullValueHandling = NullValueHandling.Ignore)]
        public long? TotalCount { get; set; }
    }

    public partial class InvoiceSettings
    {
        [JsonProperty("custom_fields")]
        public object CustomFields { get; set; }

        [JsonProperty("default_payment_method")]
        public object DefaultPaymentMethod { get; set; }

        [JsonProperty("footer")]
        public object Footer { get; set; }
    }

    public partial class Metadata
    {
    }

    public partial class Sources
    {
        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("data")]
        public List<SourcesDatum> Data { get; set; }

        [JsonProperty("has_more")]
        public bool HasMore { get; set; }

        [JsonProperty("total_count")]
        public long TotalCount { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class SourcesDatum
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("address_city")]
        public string AddressCity { get; set; }

        [JsonProperty("address_country")]
        public string AddressCountry { get; set; }

        [JsonProperty("address_line1")]
        public string AddressLine1 { get; set; }

        [JsonProperty("address_line1_check")]
        public object AddressLine1Check { get; set; }

        [JsonProperty("address_line2")]
        public object AddressLine2 { get; set; }

        [JsonProperty("address_state")]
        public string AddressState { get; set; }

        [JsonProperty("address_zip")]
        public string AddressZip { get; set; }

        [JsonProperty("address_zip_check")]
        public object AddressZipCheck { get; set; }

        [JsonProperty("brand")]
        public string Brand { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("customer")]
        public string Customer { get; set; }

        [JsonProperty("cvc_check")]
        public string CvcCheck { get; set; }

        [JsonProperty("dynamic_last4")]
        public object DynamicLast4 { get; set; }

        [JsonProperty("exp_month")]
        public long ExpMonth { get; set; }

        [JsonProperty("exp_year")]
        public long ExpYear { get; set; }

        [JsonProperty("fingerprint")]
        public string Fingerprint { get; set; }

        [JsonProperty("funding")]
        public string Funding { get; set; }

        [JsonProperty("last4")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Last4 { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("tokenization_method")]
        public object TokenizationMethod { get; set; }
    }

    public partial class Subscriptions
    {
        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("data")]
        public List<SubscriptionsDatum> Data { get; set; }

        [JsonProperty("has_more")]
        public bool HasMore { get; set; }

        [JsonProperty("total_count")]
        public long TotalCount { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class SubscriptionsDatum
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("application_fee_percent")]
        public object ApplicationFeePercent { get; set; }

        [JsonProperty("billing")]
        public string Billing { get; set; }

        [JsonProperty("billing_cycle_anchor")]
        public long BillingCycleAnchor { get; set; }

        [JsonProperty("billing_thresholds")]
        public object BillingThresholds { get; set; }

        [JsonProperty("cancel_at")]
        public object CancelAt { get; set; }

        [JsonProperty("cancel_at_period_end")]
        public bool CancelAtPeriodEnd { get; set; }

        [JsonProperty("canceled_at")]
        public object CanceledAt { get; set; }

        [JsonProperty("collection_method")]
        public string CollectionMethod { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("current_period_end")]
        public long CurrentPeriodEnd { get; set; }

        [JsonProperty("current_period_start")]
        public long CurrentPeriodStart { get; set; }

        [JsonProperty("customer")]
        public string Customer { get; set; }

        [JsonProperty("days_until_due")]
        public object DaysUntilDue { get; set; }

        [JsonProperty("default_payment_method")]
        public object DefaultPaymentMethod { get; set; }

        [JsonProperty("default_source")]
        public object DefaultSource { get; set; }

        [JsonProperty("default_tax_rates")]
        public List<object> DefaultTaxRates { get; set; }

        [JsonProperty("discount")]
        public object Discount { get; set; }

        [JsonProperty("ended_at")]
        public object EndedAt { get; set; }

        [JsonProperty("items")]
        public Items Items { get; set; }

        [JsonProperty("latest_invoice")]
        public string LatestInvoice { get; set; }

        [JsonProperty("livemode")]
        public bool Livemode { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("pending_setup_intent")]
        public object PendingSetupIntent { get; set; }

        [JsonProperty("plan")]
        public Plan Plan { get; set; }

        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("schedule")]
        public object Schedule { get; set; }

        [JsonProperty("start")]
        public long Start { get; set; }

        [JsonProperty("start_date")]
        public long StartDate { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("tax_percent")]
        public object TaxPercent { get; set; }

        [JsonProperty("trial_end")]
        public object TrialEnd { get; set; }

        [JsonProperty("trial_start")]
        public object TrialStart { get; set; }
    }

    public partial class Items
    {
        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("data")]
        public List<ItemsDatum> Data { get; set; }

        [JsonProperty("has_more")]
        public bool HasMore { get; set; }

        [JsonProperty("total_count")]
        public long TotalCount { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }
    }

    public partial class ItemsDatum
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("billing_thresholds")]
        public object BillingThresholds { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("plan")]
        public Plan Plan { get; set; }

        [JsonProperty("quantity")]
        public long Quantity { get; set; }

        [JsonProperty("subscription")]
        public string Subscription { get; set; }

        [JsonProperty("tax_rates")]
        public List<object> TaxRates { get; set; }
    }

    public partial class Plan
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("object")]
        public string Object { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }

        [JsonProperty("aggregate_usage")]
        public object AggregateUsage { get; set; }

        [JsonProperty("amount")]
        public long Amount { get; set; }

        [JsonProperty("billing_scheme")]
        public string BillingScheme { get; set; }

        [JsonProperty("created")]
        public long Created { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }

        [JsonProperty("interval")]
        public string Interval { get; set; }

        [JsonProperty("interval_count")]
        public long IntervalCount { get; set; }

        [JsonProperty("livemode")]
        public bool Livemode { get; set; }

        [JsonProperty("metadata")]
        public Metadata Metadata { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("product")]
        public string Product { get; set; }

        [JsonProperty("tiers")]
        public object Tiers { get; set; }

        [JsonProperty("tiers_mode")]
        public object TiersMode { get; set; }

        [JsonProperty("transform_usage")]
        public object TransformUsage { get; set; }

        [JsonProperty("trial_period_days")]
        public object TrialPeriodDays { get; set; }

        [JsonProperty("usage_type")]
        public string UsageType { get; set; }
    }

    public partial class Customers
    {
        public static Customers FromJson(string json) => JsonConvert.DeserializeObject<Customers>(json, PaymentAPI.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Customers self) => JsonConvert.SerializeObject(self, PaymentAPI.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class ParseStringConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            long l;
            if (Int64.TryParse(value, out l))
            {
                return l;
            }
            throw new Exception("Cannot unmarshal type long");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (long)untypedValue;
            serializer.Serialize(writer, value.ToString());
            return;
        }

        public static readonly ParseStringConverter Singleton = new ParseStringConverter();
    }
}